P = "Phong has Visa"
S1 = "If Phong can fly, Phong will go to America"
S2 = "If Phong has Visa, Phong will go to America"
S3 = "If Phong can speak English, Phong will go to America"
C = "Phong goes to America"

P = "It's hot yesterday"
S1 = "If it's hot, it will rain the next day"
S2 = "If and only if it's not rain, Nam goes outside"
S3 = "If it's not hot, Nam will go outside"
C = "Nam goes outside"

Q = "An wake up late"
R = "The traffic is flowing smooth"
S1 = "The traffic is always heavy on school day"
S2 = "If An wake up late, he will be late for school on school day"
S3 = "An only have to go to school on school day"
S4 = "If An don't have to go to school, An can't be late for school"
C = "An is late for school"